package net.lenni0451.lambdaevents;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * The abstract handler class generated by an {@link IGenerator} implementation
 */
public abstract class AHandler {

    private final Class<?> owner;
    private final Object instance;
    private final EventHandler annotation;

    /**
     * @param owner      The owner of the handler method
     * @param instance   The instance of the handler owner
     * @param annotation The {@link EventHandler} annotation of the handler method
     */
    public AHandler(@Nonnull final Class<?> owner, @Nullable final Object instance, @Nonnull final EventHandler annotation) {
        this.owner = owner;
        this.instance = instance;
        this.annotation = annotation;
    }

    /**
     * @return The owner of the handler method
     */
    @Nonnull
    public Class<?> getOwner() {
        return this.owner;
    }

    /**
     * @return The instance of the handler owner
     */
    @Nullable
    public Object getInstance() {
        return this.instance;
    }

    /**
     * @return The {@link EventHandler} annotation of the handler method
     */
    @Nonnull
    public EventHandler getAnnotation() {
        return this.annotation;
    }

    /**
     * @return If the handler is static
     */
    public boolean isStatic() {
        return this.instance == null;
    }

    /**
     * Call the event handler with the given event instance
     *
     * @param event The event instance
     */
    public abstract void call(final Object event);

}
